version: '3.3'

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

services:


  simpletodo:
    build:
      context: ./
      dockerfile: simple_todo/Dockerfile
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --no-input
        python manage.py makemigrations
        python manage.py migrate
        python manage.py create_admin
        python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    env_file:
      - simple_todo/local.env
    ports:
      - "8000:8000"
    volumes:
      - ./simple_todo:/usr/src/simple_todo/
    depends_on:
      - postgres
    networks:
      - network

  postgres:
    image: "postgres:12.2"
    env_file:
      - postgres.env
    ports:
      - target: 5432
        published: 5532
        protocol: tcp
        mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: "redis:5.0.8-alpine"
    volumes:
      - redis-data:/data
    networks:
      - network
